Repository Splitties/refreshVersions, pull requests merged in 2022-08, with the labels that each got.

#567 BundledDependenciesTest generates dependencies-notations.md
  docs/add-dependencies.md
  docs/dependencies-notations.md
  mkdocs.yml
  plugins/dependencies/src/test/kotlin/de/fayard/refreshVersions/BundledDependenciesTest.kt
  sample-android/versions.properties
  sample-multi-modules/versions.properties
Labels: size/XXL

#559 Dependency notations updates
  docs/dependencies-notations.md
  plugins/dependencies/src/main/kotlin/dependencies/JetBrains.kt
  plugins/dependencies/src/main/kotlin/dependencies/Koin.kt
  plugins/dependencies/src/main/kotlin/dependencies/KotlinX.kt
  plugins/dependencies/src/main/kotlin/dependencies/Ktor1.kt
  plugins/dependencies/src/main/kotlin/dependencies/Ktor2.kt
  plugins/dependencies/src/main/kotlin/dependencies/Spring.kt
  plugins/dependencies/src/main/kotlin/dependencies/Testing.kt
  plugins/dependencies/src/main/kotlin/dependencies/_ALL.kt
  plugins/dependencies/src/main/resources/refreshVersions-rules/androidx-version-alias-rules.txt
  plugins/dependencies/src/main/resources/refreshVersions-rules/dependency-groups-alias-rules.txt
  plugins/dependencies/src/main/resources/refreshVersions-rules/testing-version-alias-rules.txt
  plugins/dependencies/src/main/resources/removed-dependencies-versions-keys.txt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
Labels: Dependency notations, needs-review, size/XXL

#574 docs(README): Add a table of contents
  README.md
Labels: size/M

#577 New dependency notations fixup
  docs/dependencies-notations.md
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/internal/removals_replacement/RemovedDependencyNotation.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/internal/removals_replacement/RemovedDependencyNotationsHistoryParsing.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/internal/removals_replacement/ReplacementOfRemovedDependencyNotations.kt
  plugins/core/src/test/kotlin/de/fayard/refreshVersions/core/removals_replacement/RemovedDependencyNotationsHistoryParsingTest.kt
  plugins/core/src/test/resources/removals-replacement/tricky-cases/dependency-mapping.txt
  plugins/core/src/test/resources/removals-replacement/tricky-cases/gvy-input.build.gradle
  plugins/core/src/test/resources/removals-replacement/tricky-cases/gvy-output.build.gradle
  plugins/core/src/test/resources/removals-replacement/tricky-cases/kt-input.build.gradle.kts
  plugins/core/src/test/resources/removals-replacement/tricky-cases/kt-output.build.gradle.kts
  plugins/core/src/test/resources/removals-replacement/tricky-cases/revisions-history.md
  plugins/dependencies/src/main/kotlin/de/fayard/refreshVersions/RefreshVersionsPlugin.kt
  plugins/dependencies/src/main/kotlin/dependencies/AndroidX.kt
  plugins/dependencies/src/main/kotlin/dependencies/JetBrains.kt
  plugins/dependencies/src/main/kotlin/dependencies/KotlinX.kt
  plugins/dependencies/src/main/kotlin/dependencies/Ktor.kt
  plugins/dependencies/src/main/kotlin/dependencies/Ktor1.kt
  plugins/dependencies/src/main/kotlin/dependencies/Spring.kt
  plugins/dependencies/src/main/kotlin/dependencies/Square.kt
  plugins/dependencies/src/main/kotlin/dependencies/Testing.kt
  plugins/dependencies/src/main/kotlin/dependencies/_ALL.kt
  plugins/dependencies/src/main/resources/refreshVersions-rules/dependency-groups-alias-rules.txt
  plugins/dependencies/src/main/resources/refreshVersions-rules/testing-version-alias-rules.txt
  plugins/dependencies/src/main/resources/removals-revisions-history.md
  plugins/dependencies/src/main/resources/removed-dependencies-versions-keys.txt
  plugins/dependencies/src/test/kotlin/de/fayard/refreshVersions/BundledDependenciesTest.kt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
Labels: size/XXL

#556 Update Google accompanist modules
  docs/dependencies-notations.md
  plugins/dependencies/src/main/kotlin/dependencies/Google.kt
  plugins/dependencies/src/main/resources/refreshVersions-rules/google-version-alias-rules.txt
  plugins/dependencies/src/main/resources/removals-revisions-history.md
  plugins/dependencies/src/main/resources/removed-dependencies-versions-keys.txt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
Labels: Dependency notations, needs-review, size/L
