Repository Splitties/refreshVersions, pull requests merged in 2022-07, with the labels that each got.

#560 Polish BundledDependenciesTest for first-time contributors
  plugins/dependencies/src/main/resources/refreshVersions-rules/dependency-groups-alias-rules.txt
  plugins/dependencies/src/main/resources/removed-dependencies-versions-keys.txt
  plugins/dependencies/src/test/kotlin/de/fayard/refreshVersions/BundledDependenciesTest.kt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
Labels: size/L

#561 Docs dependency notations
  docs/add-dependencies.md
  docs/dependencies-notations.md
  mkdocs.yml
  plugins/dependencies/src/test/kotlin/de/fayard/refreshVersions/BundledDependenciesTest.kt
Labels: size/XXL

#566 Complete OkHttp dependencies.
  plugins/dependencies/src/main/kotlin/dependencies/Square.kt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
  sample-android/versions.properties
  sample-kotlin-js/versions.properties
  sample-kotlin/versions.properties
Labels: size/M

#564 Dependency Notation for Horologist.
  plugins/dependencies/src/main/kotlin/dependencies/Google.kt
  plugins/dependencies/src/main/resources/refreshVersions-rules/dependency-groups-alias-rules.txt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
Labels: size/M
