Repository Splitties/refreshVersions, pull requests merged in 2022-10, with the labels that each got.

#633 Fixed a mistake
  docs/index.md
Labels: size/XS

#583 Add KOTLIN_SCRIPTS feature flag
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/FeatureFlag.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/RefreshVersionsCleanupTask.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/RefreshVersionsTask.kt
  sample-kotlin/settings.gradle.kts
Labels: size/M, not-for-this-release

#642 Prepare for release 0.51.0
  CHANGELOG.md
  README.md
  docs/dependency-notations.md
  mkdocs.yml
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/DependencyNotations.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/FeatureFlag.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/RefreshVersionsCleanupTask.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/RefreshVersionsTask.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/Version.kt
  plugins/core/src/test/kotlin/de/fayard/refreshVersions/core/VersionComparatorTest.kt
  plugins/core/src/test/resources/versions-comparison/com.google.guava.txt
  plugins/core/src/test/resources/versions-comparison/org.eclipse.jgit.txt
  plugins/core/src/test/resources/versions-comparison/org.jetbrains.kotlin.txt
  plugins/core/src/test/resources/versions-stability-level/Alpha.txt
  plugins/core/src/test/resources/versions-stability-level/Beta.txt
  plugins/core/src/test/resources/versions-stability-level/Development.txt
  plugins/core/src/test/resources/versions-stability-level/EarlyAccessProgram.txt
  plugins/core/src/test/resources/versions-stability-level/Milestone.txt
  plugins/core/src/test/resources/versions-stability-level/Preview.txt
  plugins/core/src/test/resources/versions-stability-level/ReleaseCandidate.txt
  plugins/core/src/test/resources/versions-stability-level/Snapshot.txt
  plugins/core/src/test/resources/versions-stability-level/Stable.txt
  plugins/dependencies/src/main/kotlin/de/fayard/refreshVersions/Annotations.kt
  plugins/dependencies/src/main/kotlin/dependencies/AndroidX.kt
  plugins/dependencies/src/main/kotlin/dependencies/Firebase.kt
  plugins/dependencies/src/main/resources/refreshVersions-rules/androidx-version-alias-rules.txt
  plugins/dependencies/src/main/resources/version-to-removals-revision-mapping.txt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
  plugins/version.txt
  sample-groovy/versions.properties
  sample-kotlin/settings.gradle.kts
Labels: size/XXL
