Repository Splitties/refreshVersions, pull requests merged in 2022-09, with the labels that each got.

#590 Polish release documentation
  CHANGELOG.md
  README.md
  plugins/core/src/test/kotlin/de/fayard/refreshVersions/core/TomlLineTest.kt
Labels: size/M

#594 [Issue-593] Dependency notations for CashApp: Molecule
  docs/dependencies-notations.md
  plugins/dependencies/src/main/kotlin/dependencies/CashApp.kt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
Labels: size/M

#598 Fix missing newline, breaking markdown parsing of lists
  docs/migrate.md
Labels: size/XS

#601 Draft article moved to refreshVersions wiki
  README.md
Labels: size/XS

#603 Prepare for release 0.50.1
  CHANGELOG.md
  README.md
  Releasing.main.kts
  mkdocs.yml
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/internal/VersionsCatalogs.kt
  plugins/dependencies/src/main/kotlin/de/fayard/refreshVersions/RefreshVersionsMigrateTask.kt
  plugins/dependencies/src/main/kotlin/de/fayard/refreshVersions/internal/VersionsCatalogGeneration.kt
  plugins/dependencies/src/main/resources/version-to-removals-revision-mapping.txt
  plugins/version.txt
Labels: size/M

#614 Move the dependency notations webpage generating test
  Releasing.main.kts
  docs/add-dependencies.md
  docs/dependencies-notations.md
  docs/dependency-notations.md
  mkdocs.yml
  plugins/dependencies/build.gradle.kts
  plugins/dependencies/src/prePublishTest/kotlin/DependencyNotationsWebpageUpdateTest.kt
  plugins/dependencies/src/prePublishTest/kotlin/RemovedDependencyNotationsHistoryCompletenessTest.kt
  plugins/dependencies/src/prePublishTest/kotlin/pluginsVersion.kt
  plugins/dependencies/src/test/kotlin/de/fayard/refreshVersions/BundledDependenciesTest.kt
Labels: size/XXL

#611 Add Spring.boot.web notation
  plugins/dependencies/src/main/kotlin/dependencies/Spring.kt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
Labels: size/XS

#613 [Issue-605] Dependency notation for kotlinx.serialization.json.okio
  plugins/dependencies/src/main/kotlin/dependencies/KotlinX.kt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
Labels: size/S

#602 [Issue-518] Dependency notations for Apollo Kotlin
  plugins/dependencies/src/main/kotlin/dependencies/ApolloGraphQL.kt
  plugins/dependencies/src/main/kotlin/dependencies/_ALL.kt
  plugins/dependencies/src/main/resources/refreshVersions-rules/dependency-groups-alias-rules.txt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
Labels: size/L

#616 [Issue-615] Removed `molecule-testing` artifact
  plugins/dependencies/src/main/kotlin/dependencies/CashApp.kt
  plugins/dependencies/src/main/resources/removals-revisions-history.md
  plugins/dependencies/src/main/resources/removed-dependencies-versions-keys.txt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
Labels: size/S

#622 [Issue-621] Updated docs for Import -> Link Gradle Project terminology
  docs/contributing/submitting-prs/dev-env.md
  docs/img/import-plugins-gradle-project.png
  docs/img/link-plugins-gradle-project.png
Labels: size/XS

#623 Reduced image size of docs/img/*.png by using TinyPNG
  docs/img/dependencies_constants_autocomplete_1.png
  docs/img/dependencies_constants_autocomplete_2.png
  docs/img/execute-gradle-task.png
  docs/img/jetbrains_package_search_screenshot.png
  docs/img/kotlin-libraries-playground.png
  docs/img/link-plugins-gradle-project.png
  docs/img/screencast.png
  docs/img/versions.properties.png
  docs/img/versions.properties_step00.png
  docs/img/versions.properties_step01.png
  docs/img/versions.properties_step02.png
  docs/img/versions.properties_step03.png
Labels: size/XS

#625 Prepare for release 0.50.2
  CHANGELOG.md
  CODEOWNERS
  README.md
  Releasing.main.kts
  docs/add-dependencies.md
  docs/contributing/submitting-prs/dev-env.md
  docs/dependencies-notations.md
  docs/dependency-notations.md
  docs/img/dependencies_constants_autocomplete_1.png
  docs/img/dependencies_constants_autocomplete_2.png
  docs/img/execute-gradle-task.png
  docs/img/import-plugins-gradle-project.png
  docs/img/jetbrains_package_search_screenshot.png
  docs/img/kotlin-libraries-playground.png
  docs/img/link-plugins-gradle-project.png
  docs/img/screencast.png
  docs/img/versions.properties.png
  docs/img/versions.properties_step00.png
  docs/img/versions.properties_step01.png
  docs/img/versions.properties_step02.png
  docs/img/versions.properties_step03.png
  mkdocs.yml
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/FeatureFlag.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/RefreshVersionsCleanupTask.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/StabilityLevel.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/Version.kt
  plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/internal/UsedVersionForTracker.kt
  plugins/core/src/test/kotlin/de/fayard/refreshVersions/core/StabilityLevelTest.kt
  plugins/core/src/test/kotlin/de/fayard/refreshVersions/core/VersionComparatorTest.kt
  plugins/core/src/test/resources/versions-comparison/kotlinx.coroutines.txt
  plugins/core/src/test/resources/versions-comparison/org.eclipse.jgit
  plugins/core/src/test/resources/versions-comparison/versions-suffix-simple.txt
  plugins/dependencies/build.gradle.kts
  plugins/dependencies/src/main/kotlin/de/fayard/refreshVersions/RefreshVersionsPlugin.kt
  plugins/dependencies/src/main/kotlin/dependencies/AndroidX.kt
  plugins/dependencies/src/main/kotlin/dependencies/ApolloGraphQL.kt
  plugins/dependencies/src/main/kotlin/dependencies/CashApp.kt
  plugins/dependencies/src/main/kotlin/dependencies/Google.kt
  plugins/dependencies/src/main/kotlin/dependencies/KotlinX.kt
  plugins/dependencies/src/main/kotlin/dependencies/Spring.kt
  plugins/dependencies/src/main/kotlin/dependencies/_ALL.kt
  plugins/dependencies/src/main/resources/refreshVersions-rules/dependency-groups-alias-rules.txt
  plugins/dependencies/src/main/resources/removals-revisions-history.md
  plugins/dependencies/src/main/resources/removed-dependencies-versions-keys.txt
  plugins/dependencies/src/main/resources/version-to-removals-revision-mapping.txt
  plugins/dependencies/src/prePublishTest/kotlin/DependencyNotationsWebpageUpdateTest.kt
  plugins/dependencies/src/prePublishTest/kotlin/RemovedDependencyNotationsHistoryCompletenessTest.kt
  plugins/dependencies/src/prePublishTest/kotlin/pluginsVersion.kt
  plugins/dependencies/src/test/kotlin/de/fayard/refreshVersions/BundledDependenciesTest.kt
  plugins/dependencies/src/test/resources/bundled-dependencies-validated.txt
  plugins/dependencies/src/test/resources/dependencies-mapping-validated.txt
  plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
  plugins/version.txt
  sample-kotlin/settings.gradle.kts
Labels: size/XXL
